PREFIJOS_TELEFONICOS = [
    {"code": "AF", "label": "Afganistán", "dial": "93"},
    {"code": "AL", "label": "Albania", "dial": "355"},
    {"code": "DZ", "label": "Argelia", "dial": "213"},
    {"code": "AD", "label": "Andorra", "dial": "376"},
    {"code": "AO", "label": "Angola", "dial": "244"},
    {"code": "AG", "label": "Antigua y Barbuda", "dial": "1"},
    {"code": "AR", "label": "Argentina", "dial": "54"},
    {"code": "AM", "label": "Armenia", "dial": "374"},
    {"code": "AU", "label": "Australia", "dial": "61"},
    {"code": "AT", "label": "Austria", "dial": "43"},
    {"code": "AZ", "label": "Azerbaiyán", "dial": "994"},
    {"code": "BS", "label": "Bahamas", "dial": "1"},
    {"code": "BH", "label": "Baréin", "dial": "973"},
    {"code": "BD", "label": "Bangladés", "dial": "880"},
    {"code": "BB", "label": "Barbados", "dial": "1"},
    {"code": "BY", "label": "Bielorrusia", "dial": "375"},
    {"code": "BE", "label": "Bélgica", "dial": "32"},
    {"code": "BZ", "label": "Belice", "dial": "501"},
    {"code": "BJ", "label": "Benín", "dial": "229"},
    {"code": "BT", "label": "Bután", "dial": "975"},
    {"code": "BO", "label": "Bolivia", "dial": "591"},
    {"code": "BA", "label": "Bosnia y Herzegovina", "dial": "387"},
    {"code": "BW", "label": "Botsuana", "dial": "267"},
    {"code": "BR", "label": "Brasil", "dial": "55"},
    {"code": "BN", "label": "Brunéi", "dial": "673"},
    {"code": "BG", "label": "Bulgaria", "dial": "359"},
    {"code": "BF", "label": "Burkina Faso", "dial": "226"},
    {"code": "BI", "label": "Burundi", "dial": "257"},
    {"code": "KH", "label": "Camboya", "dial": "855"},
    {"code": "CM", "label": "Camerún", "dial": "237"},
    {"code": "CA", "label": "Canadá", "dial": "1"},
    {"code": "CV", "label": "Cabo Verde", "dial": "238"},
    {"code": "CF", "label": "República Centroafricana", "dial": "236"},
    {"code": "TD", "label": "Chad", "dial": "235"},
    {"code": "CL", "label": "Chile", "dial": "56"},
    {"code": "CN", "label": "China", "dial": "86"},
    {"code": "CO", "label": "Colombia", "dial": "57"},
    {"code": "KM", "label": "Comoras", "dial": "269"},
    {"code": "CG", "label": "Congo", "dial": "242"},
    {"code": "CD", "label": "República Democrática del Congo", "dial": "243"},
    {"code": "CR", "label": "Costa Rica", "dial": "506"},
    {"code": "CI", "label": "Costa de Marfil", "dial": "225"},
    {"code": "HR", "label": "Croacia", "dial": "385"},
    {"code": "CU", "label": "Cuba", "dial": "53"},
    {"code": "CY", "label": "Chipre", "dial": "357"},
    {"code": "CZ", "label": "República Checa", "dial": "420"},
    {"code": "DK", "label": "Dinamarca", "dial": "45"},
    {"code": "DJ", "label": "Yibuti", "dial": "253"},
    {"code": "DM", "label": "Dominica", "dial": "1"},
    {"code": "DO", "label": "República Dominicana", "dial": "1"},
    {"code": "EC", "label": "Ecuador", "dial": "593"},
    {"code": "EG", "label": "Egipto", "dial": "20"},
    {"code": "SV", "label": "El Salvador", "dial": "503"},
    {"code": "GQ", "label": "Guinea Ecuatorial", "dial": "240"},
    {"code": "ER", "label": "Eritrea", "dial": "291"},
    {"code": "EE", "label": "Estonia", "dial": "372"},
    {"code": "SZ", "label": "Esuatini", "dial": "268"},
    {"code": "ET", "label": "Etiopía", "dial": "251"},
    {"code": "FJ", "label": "Fiyi", "dial": "679"},
    {"code": "FI", "label": "Finlandia", "dial": "358"},
    {"code": "FR", "label": "Francia", "dial": "33"},
    {"code": "GA", "label": "Gabón", "dial": "241"},
    {"code": "GM", "label": "Gambia", "dial": "220"},
    {"code": "GE", "label": "Georgia", "dial": "995"},
    {"code": "DE", "label": "Alemania", "dial": "49"},
    {"code": "GH", "label": "Ghana", "dial": "233"},
    {"code": "GR", "label": "Grecia", "dial": "30"},
    {"code": "GD", "label": "Granada", "dial": "1"},
    {"code": "GT", "label": "Guatemala", "dial": "502"},
    {"code": "GN", "label": "Guinea", "dial": "224"},
    {"code": "GW", "label": "Guinea-Bisáu", "dial": "245"},
    {"code": "GY", "label": "Guyana", "dial": "592"},
    {"code": "HT", "label": "Haití", "dial": "509"},
    {"code": "HN", "label": "Honduras", "dial": "504"},
    {"code": "HU", "label": "Hungría", "dial": "36"},
    {"code": "IS", "label": "Islandia", "dial": "354"},
    {"code": "IN", "label": "India", "dial": "91"},
    {"code": "ID", "label": "Indonesia", "dial": "62"},
    {"code": "IR", "label": "Irán", "dial": "98"},
    {"code": "IQ", "label": "Irak", "dial": "964"},
    {"code": "IE", "label": "Irlanda", "dial": "353"},
    {"code": "IL", "label": "Israel", "dial": "972"},
    {"code": "IT", "label": "Italia", "dial": "39"},
    {"code": "JM", "label": "Jamaica", "dial": "1"},
    {"code": "JP", "label": "Japón", "dial": "81"},
    {"code": "JO", "label": "Jordania", "dial": "962"},
    {"code": "KZ", "label": "Kazajistán", "dial": "7"},
    {"code": "KE", "label": "Kenia", "dial": "254"},
    {"code": "KR", "label": "Corea del Sur", "dial": "82"},
    {"code": "KW", "label": "Kuwait", "dial": "965"},
    {"code": "KG", "label": "Kirguistán", "dial": "996"},
    {"code": "LA", "label": "Laos", "dial": "856"},
    {"code": "LV", "label": "Letonia", "dial": "371"},
    {"code": "LB", "label": "Líbano", "dial": "961"},
    {"code": "LS", "label": "Lesoto", "dial": "266"},
    {"code": "LR", "label": "Liberia", "dial": "231"},
    {"code": "LY", "label": "Libia", "dial": "218"},
    {"code": "LI", "label": "Liechtenstein", "dial": "423"},
    {"code": "LT", "label": "Lituania", "dial": "370"},
    {"code": "LU", "label": "Luxemburgo", "dial": "352"},
    {"code": "MG", "label": "Madagascar", "dial": "261"},
    {"code": "MW", "label": "Malaui", "dial": "265"},
    {"code": "MY", "label": "Malasia", "dial": "60"},
    {"code": "MV", "label": "Maldivas", "dial": "960"},
    {"code": "ML", "label": "Malí", "dial": "223"},
    {"code": "MT", "label": "Malta", "dial": "356"},
    {"code": "MX", "label": "México", "dial": "52"},
    {"code": "MD", "label": "Moldavia", "dial": "373"},
    {"code": "MC", "label": "Mónaco", "dial": "377"},
    {"code": "MN", "label": "Mongolia", "dial": "976"},
    {"code": "ME", "label": "Montenegro", "dial": "382"},
    {"code": "MA", "label": "Marruecos", "dial": "212"},
    {"code": "MZ", "label": "Mozambique", "dial": "258"},
    {"code": "MM", "label": "Myanmar", "dial": "95"},
    {"code": "NA", "label": "Namibia", "dial": "264"},
    {"code": "NP", "label": "Nepal", "dial": "977"},
    {"code": "NL", "label": "Países Bajos", "dial": "31"},
    {"code": "NZ", "label": "Nueva Zelanda", "dial": "64"},
    {"code": "NI", "label": "Nicaragua", "dial": "505"},
    {"code": "NE", "label": "Níger", "dial": "227"},
    {"code": "NG", "label": "Nigeria", "dial": "234"},
    {"code": "NO", "label": "Noruega", "dial": "47"},
    {"code": "OM", "label": "Omán", "dial": "968"},
    {"code": "PK", "label": "Pakistán", "dial": "92"},
    {"code": "PA", "label": "Panamá", "dial": "507"},
    {"code": "PY", "label": "Paraguay", "dial": "595"},
    {"code": "PE", "label": "Perú", "dial": "51"},
    {"code": "PH", "label": "Filipinas", "dial": "63"},
    {"code": "PL", "label": "Polonia", "dial": "48"},
    {"code": "PT", "label": "Portugal", "dial": "351"},
    {"code": "QA", "label": "Catar", "dial": "974"},
    {"code": "RO", "label": "Rumanía", "dial": "40"},
    {"code": "RU", "label": "Rusia", "dial": "7"},
    {"code": "SA", "label": "Arabia Saudita", "dial": "966"},
    {"code": "SN", "label": "Senegal", "dial": "221"},
    {"code": "RS", "label": "Serbia", "dial": "381"},
    {"code": "SG", "label": "Singapur", "dial": "65"},
    {"code": "SK", "label": "Eslovaquia", "dial": "421"},
    {"code": "SI", "label": "Eslovenia", "dial": "386"},
    {"code": "ZA", "label": "Sudáfrica", "dial": "27"},
    {"code": "ES", "label": "España", "dial": "34"},
    {"code": "LK", "label": "Sri Lanka", "dial": "94"},
    {"code": "SE", "label": "Suecia", "dial": "46"},
    {"code": "CH", "label": "Suiza", "dial": "41"},
    {"code": "SY", "label": "Siria", "dial": "963"},
    {"code": "TW", "label": "Taiwán", "dial": "886"},
    {"code": "TJ", "label": "Tayikistán", "dial": "992"},
    {"code": "TZ", "label": "Tanzania", "dial": "255"},
    {"code": "TH", "label": "Tailandia", "dial": "66"},
    {"code": "TG", "label": "Togo", "dial": "228"},
    {"code": "TT", "label": "Trinidad y Tobago", "dial": "1"},
    {"code": "TN", "label": "Túnez", "dial": "216"},
    {"code": "TR", "label": "Turquía", "dial": "90"},
    {"code": "TM", "label": "Turkmenistán", "dial": "993"},
    {"code": "UG", "label": "Uganda", "dial": "256"},
    {"code": "UA", "label": "Ucrania", "dial": "380"},
    {"code": "AE", "label": "Emiratos Árabes Unidos", "dial": "971"},
    {"code": "GB", "label": "Reino Unido", "dial": "44"},
    {"code": "US", "label": "Estados Unidos", "dial": "1"},
    {"code": "UY", "label": "Uruguay", "dial": "598"},
    {"code": "UZ", "label": "Uzbekistán", "dial": "998"},
    {"code": "VE", "label": "Venezuela", "dial": "58"},
    {"code": "VN", "label": "Vietnam", "dial": "84"},
    {"code": "YE", "label": "Yemen", "dial": "967"},
    {"code": "ZM", "label": "Zambia", "dial": "260"},
    {"code": "ZW", "label": "Zimbabue", "dial": "263"}
]